In [ ]:
s = "Hi there suriya"

In [ ]:
s.split(' ')

['Hi', 'there', 'suriya']

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
print('The diameter of the {} is {} kilometers'.format(planet, diameter))

The diameter of the Earth is 12742 kilometers


In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'suriya']}]}]}

In [ ]:
d['k1'][3]['tricky'][3]['target'][3]

'suriya'

In [ ]:
import numpy as np

4.1. Create an array of 18 zeros?

4.2. Create an array of 10 ten?

In [ ]:
np.zeros(18)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [ ]:
np.zeros(10) + 10

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

Create an array of all the even integers from 20 to 41?

In [ ]:
np.arange(20,41,2)

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Concatenates a and b



a = np.array([1, 2, 4]), b = np.array([7, 5, 6])

In [ ]:
a = np.array([1, 2, 4])
b = np.array([7, 5, 6])

In [ ]:
np.concatenate((a,b))

array([1, 2, 4, 7, 5, 6])


Pandas

Create a dataframe with 4 rows and 2 columns.

In [ ]:
import pandas as pd

In [ ]:
data = np.arange(0,8).reshape(4,2)
df = pd.DataFrame(data)
df

0  1
0  0  1
1  2  3
2  4  5
3  6  7

Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
df = pd.date_range(start='20/3/23', end='20/09/23')
df

DatetimeIndex(['2023-03-20', '2023-03-21', '2023-03-22', '2023-03-23',
               '2023-03-24', '2023-03-25', '2023-03-26', '2023-03-27',
               '2023-03-28', '2023-03-29',
               ...
               '2023-09-11', '2023-09-12', '2023-09-13', '2023-09-14',
               '2023-09-15', '2023-09-16', '2023-09-17', '2023-09-18',
               '2023-09-19', '2023-09-20'],
              dtype='datetime64[ns]', length=185, freq='D')

Create 2D list to DataFrame

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 28], [3, 'ccc', 24]]

In [ ]:
df = pd.DataFrame(lists)

In [ ]:
df

0    1   2
0  1  aaa  22
1  2  bbb  28
2  3  ccc  24