In [1]:
s = "Hi there manoj!"

In [2]:
s.split(' ')

['Hi', 'there', 'manoj!']

In [3]:
planet = "Earth"
diameter = 12745

In [4]:
print('The diameter of the {} is {} kilometers'.format(planet, diameter))

The diameter of the Earth is 12745 kilometers


In [6]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'manoj']}]}]}

In [7]:
d['k1'][3]['tricky'][3]['target'][3]

'manoj'

In [9]:
import numpy as np

 Create an array of 15 zeros?

 Create an array of 7 fives?

In [10]:
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros(10) + 7

array([7., 7., 7., 7., 7., 7., 7., 7., 7., 7.])

Create an array of all the even integers from 20 to 39?

In [12]:
np.arange(20,39,2)

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

Create a 3x3 matrix with values ranging from 0 to 9

In [13]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Concatenates a and b

a = np.array([1, 2, 4]), b = np.array([7, 5, 6])

In [41]:
a = np.array([1, 2, 4])
b = np.array([8, 5, 6])

In [42]:
np.concatenate((a,b))

array([1, 2, 4, 8, 5, 6])


Pandas

Create a dataframe with 4 rows and 2 columns.

In [43]:
import pandas as pd

In [44]:
data = np.arange(0,8).reshape(4,2)
df = pd.DataFrame(data)
df

0  1
0  0  1
1  2  3
2  4  5
3  6  7

Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [46]:
df = pd.date_range(start='20/1/23', end='10/03/23')
df

DatetimeIndex(['2023-01-20', '2023-01-21', '2023-01-22', '2023-01-23',
               '2023-01-24', '2023-01-25', '2023-01-26', '2023-01-27',
               '2023-01-28', '2023-01-29',
               ...
               '2023-09-24', '2023-09-25', '2023-09-26', '2023-09-27',
               '2023-09-28', '2023-09-29', '2023-09-30', '2023-10-01',
               '2023-10-02', '2023-10-03'],
              dtype='datetime64[ns]', length=257, freq='D')

Create 2D list to DataFrame

In [49]:
lists = [[1, 'aaa', 22], [2, 'bbb', 20], [3, 'ccc', 24]]

In [48]:
df = pd.DataFrame(lists)

In [51]:
df

0    1   2
0  1  aaa  22
1  2  bbb  28
2  3  ccc  24